#!/bin/bash

docker run \
-e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
-e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
-e AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN \
-e AWS_REGION=us-east-2 \
-e ANALYTICS_BUCKET=$ANALYTICS_BUCKET \
-e ANALYTICS_OUTPUT_BUCKET=$ANALYTICS_OUTPUT_BUCKET \
-e NEXT_GEM_DATA_CATALOG_DATABASE_NAME=$NEXT_GEM_DATA_CATALOG_DATABASE_NAME \
--network=host \
next_gem_catalog_mcp_server