---  
name: General Issue    
about: Ask a question or request a feature    
title: "[Issue] "    
labels: ""    
assignees: 'deanwampler'
project: "FA5: OTDI Tasks"
---    

## Description
Please provide a clear and concise description of the question you have or feature you're requesting.

### Feature Details (if applicable)
If this is a feature request, please describe:
- What you want to happen
- Why this would be valuable
- Any alternative solutions you've considered

### Question Details (if applicable)
If this is a question, please provide:
- What you're trying to accomplish
- What you've tried so far
- Any relevant code snippets

### Additional Context
Add any other context or screenshots that might be helpful.
    
---    

## Checklist
- [ ] I have searched the existing issues to ensure this isn't a duplicate
- [ ] I have checked the documentation and README for a solution
- [ ] I have provided clear and concise information about the issue    